### ISSUE TITLE
验证码错误

### ISSUE THREAD

**Issue by timiho** [MasterJoyHunan/go-admin-cms#3]
如题

**Comment by MasterJoyHunan** [comment]
你自己部署之后,本地会出现验证码错误?

**Comment by timiho** [comment]
是的，这个问题找到原因了，没有用localhost 用了IP的原因

但是我自建一个admin用户登录，只有一个首页菜单。


能提供一下SQL四张表的内容吗 非常感谢&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年8月29日(星期一) 下午4:31
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [MasterJoyHunan/go-admin-cms] 验证码错误 (Issue #3)





 
你自己部署之后,本地会出现验证码错误?

**Comment by timiho** [comment]
3q




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年8月29日(星期一) 下午5:21
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [MasterJoyHunan/go-admin-cms] 验证码错误 (Issue #3)





 
程序启动时,添加参数 -init, 会自动生成表结构
 https://github.com/MasterJoyHunan/go-admin-cms/blob/d011b76b2b615a33e3e2394158de76d1bc01546b/go/model/common.go#L39
